"""demo three test models

Revision ID: dc08d3017900
Revises: 9c1f2a7b4e3d
Create Date: 2026-05-27 17:32:36.306474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'dc08d3017900'
down_revision: Union[str, Sequence[str], None] = '9c1f2a7b4e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreignkeymodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('relationmodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('detailmodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('big_int_field', sa.BigInteger(), nullable=True),
    sa.Column('binary_field', sa.LargeBinary(), nullable=True),
    sa.Column('boolean_field', sa.Boolean(), nullable=True),
    sa.Column('char_enum_field', sa.Enum('option1', 'option2', 'option3'), nullable=True),
    sa.Column('char_field', sa.String(length=255), nullable=True),
    sa.Column('date_field', sa.Date(), nullable=True),
    sa.Column('date_time_field', sa.DateTime(), nullable=True),
    sa.Column('decimal_field', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('float_field', sa.Float(), nullable=True),
    sa.Column('int_enum_field', sa.Integer(), nullable=True),
    sa.Column('int_field', sa.Integer(), nullable=True),
    sa.Column('json_field', sa.JSON(), nullable=True),
    sa.Column('small_integer_field', sa.SmallInteger(), nullable=True),
    sa.Column('text_field', sa.Text(), nullable=True),
    sa.Column('time_field', sa.Time(), nullable=True),
    sa.Column('time_delta_field', sa.Integer(), nullable=True),
    sa.Column('uuid_field', sa.String(length=36), nullable=True),
    sa.Column('foreign_model_id', sa.Integer(), nullable=True),
    sa.Column('one_to_one_relation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foreign_model_id'], ['foreignkeymodel.id'], ),
    sa.ForeignKeyConstraint(['one_to_one_relation_id'], ['relationmodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('one_to_one_relation_id')
    )
    op.create_table('detail_relation',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['detailmodel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_id'], ['relationmodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detail_id', 'relation_id')
    )
    op.drop_table('testmodel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testmodel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('big_int_field', sa.INTEGER(), nullable=True),
    sa.Column('binary_field', sa.BLOB(), nullable=True),
    sa.Column('boolean_field', sa.BOOLEAN(), nullable=True),
    sa.Column('char_enum_field', sa.VARCHAR(length=7), nullable=True),
    sa.Column('char_field', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_field', sa.DATE(), nullable=True),
    sa.Column('date_time_field', sa.DATETIME(), nullable=True),
    sa.Column('decimal_field', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('float_field', sa.FLOAT(), nullable=True),
    sa.Column('int_enum_field', sa.INTEGER(), nullable=True),
    sa.Column('int_field', sa.INTEGER(), nullable=True),
    sa.Column('json_field', sqlite.JSON(), nullable=True),
    sa.Column('small_integer_field', sa.SMALLINT(), nullable=True),
    sa.Column('text_field', sa.TEXT(), nullable=True),
    sa.Column('time_delta_field', sa.INTEGER(), nullable=True),
    sa.Column('uuid_field', sa.VARCHAR(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('detail_relation')
    op.drop_table('detailmodel')
    op.drop_table('relationmodel')
    op.drop_table('foreignkeymodel')
    # ### end Alembic commands ###
