from apps.udadmin.utils.ui_tools import ActionSchema, UiInfo
from . import models as md


ForeignKeyModelUi = UiInfo(
    model=md.ForeignKeyModel,
    list_display=["*"],
    list_filter=["id", "name", "code"],
    search_fields=["name", "code", "description"],
    editable_fields=["name", "code", "description"],
)


RelationModelUi = UiInfo(
    model=md.RelationModel,
    list_display=["*"],
    list_filter=["id", "name", "category"],
    search_fields=["name", "category", "remark"],
    editable_fields=["name", "category", "remark"],
)


DetailModelUi = UiInfo(
    model=md.DetailModel,
    list_display=["*"],
    list_filter=[
        "id",
        "big_int_field",
        "binary_field",
        "boolean_field",
        "char_enum_field",
        "char_field",
        "date_field",
        "date_time_field",
        "decimal_field",
        "float_field",
        "int_enum_field",
        "int_field",
        "small_integer_field",
        "time_field",
        "uuid_field",
        "foreign_model_id",
        "one_to_one_relation_id",
    ],
    search_fields=["char_field", "text_field", "uuid_field"],
    form_cmps={"binary_field": "CharField"},
    editable_fields=[
        "big_int_field",
        "binary_field",
        "boolean_field",
        "char_enum_field",
        "char_field",
        "date_field",
        "date_time_field",
        "decimal_field",
        "float_field",
        "int_enum_field",
        "int_field",
        "json_field",
        "small_integer_field",
        "text_field",
        "time_field",
        "time_delta_field",
        "uuid_field",
        "foreign_model_id",
        "one_to_one_relation_id",
    ],
    custom_actions=[
        ActionSchema(
            key="detail_row_preview",
            label="行id",
            # icon="EditOutlined",
            type="info",
            placement="row",
            action_key="demo.detail.preview_row",
            url="/demo/actions/detail/preview_row",
            param="id",
            permission="demo:DetailModel:action:preview_row",
        ),
        ActionSchema(
            key="detail_row_record",
            label="行对象",
            # icon="SaveOutlined",
            type="success",
            placement="row",
            action_key="demo.detail.preview_record",
            url="/demo/actions/detail/preview_record",
            param="record",
            permission="demo:DetailModel:action:preview_record",
        ),
        ActionSchema(
            key="detail_toolbar_summary",
            label="已选id",
            # icon="ReloadOutlined",
            type="primary",
            placement="toolbar",
            action_key="demo.detail.show_context",
            url="/demo/actions/detail/show_context",
            param="id",
            permission="demo:DetailModel:action:show_context",
        ),
        ActionSchema(
            key="detail_toolbar_records",
            label="已选行",
            # icon="EditOutlined",
            type="warning",
            placement="toolbar",
            action_key="demo.detail.show_records",
            url="/demo/actions/detail/show_records",
            param="record",
            permission="demo:DetailModel:action:show_records",
        ),
    ],
)
